CREATE TABLE course_students
(
    course_id  BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    CONSTRAINT pk_course_students PRIMARY KEY (course_id, student_id)
);

CREATE TABLE courses
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    description   VARCHAR(500),
    academic_year VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP                               NOT NULL,
    updated_at    TIMESTAMP,
    lab_weight    INT                                     NOT NULL,
    lab_count     INT                                     NOT NULL,
    exam_weight   INT                                     NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE exam_submissions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id     BIGINT                                  NOT NULL,
    exam_id        BIGINT                                  NOT NULL,
    task_id        BIGINT,
    submission_url VARCHAR(500),
    answer         VARCHAR(1000),
    submitted_at   TIMESTAMP,
    grade          DOUBLE PRECISION,
    graded_at      TIMESTAMP,
    grader_notes   VARCHAR(1000),
    created_at     TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_exam_submissions PRIMARY KEY (id)
);

CREATE TABLE exams
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(200)                            NOT NULL,
    description      VARCHAR(1000),
    scheduled_date   TIMESTAMP                               NOT NULL,
    duration_minutes INT,
    created_at       TIMESTAMP                               NOT NULL,
    course_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_exams PRIMARY KEY (id)
);

CREATE TABLE lab_submissions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submission_url  VARCHAR(500),
    notes           VARCHAR(1000),
    submitted_at    TIMESTAMP                               NOT NULL,
    raw_grade       DOUBLE PRECISION,
    final_grade     DOUBLE PRECISION,
    is_late         BOOLEAN,
    penalty_applied DOUBLE PRECISION,
    graded_at       TIMESTAMP,
    grader_notes    VARCHAR(1000),
    student_id      BIGINT                                  NOT NULL,
    lab_work_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_lab_submissions PRIMARY KEY (id)
);

CREATE TABLE lab_works
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lab_number             INT                                     NOT NULL,
    title                  VARCHAR(200)                            NOT NULL,
    description            VARCHAR(1000),
    deadline               TIMESTAMP                               NOT NULL,
    allows_late_submission BOOLEAN                                 NOT NULL,
    late_penalty_per_day   DOUBLE PRECISION,
    max_late_days          INT,
    created_at             TIMESTAMP                               NOT NULL,
    course_id              BIGINT                                  NOT NULL,
    CONSTRAINT pk_lab_works PRIMARY KEY (id)
);

CREATE TABLE students
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name     VARCHAR(50)                             NOT NULL,
    last_name      VARCHAR(50)                             NOT NULL,
    email          VARCHAR(100)                            NOT NULL,
    student_number VARCHAR(20)                             NOT NULL,
    user_id        BIGINT,
    created_at     TIMESTAMP                               NOT NULL,
    updated_at     TIMESTAMP,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    variant_number INT                                     NOT NULL,
    title          VARCHAR(200)                            NOT NULL,
    description    VARCHAR(2000)                           NOT NULL,
    created_at     TIMESTAMP                               NOT NULL,
    exam_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(50)                             NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    created_at TIMESTAMP                               NOT NULL,
--     CONSTRAINT pk_users PRIMARY KEY (id)
    CONSTRAINT chk_role CHECK (role IN ('ADMIN', 'STUDENT'))
);

ALTER TABLE lab_submissions
    ADD CONSTRAINT uc_2917a71cc12519bd8e645177b UNIQUE (student_id, lab_work_id);

ALTER TABLE courses
    ADD CONSTRAINT uc_41bbf0c98c8a377d707bd0a08 UNIQUE (name, academic_year);

ALTER TABLE students
    ADD CONSTRAINT uc_66c8f1cdf2fa20f209d8e9362 UNIQUE (student_number);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

ALTER TABLE exam_submissions
    ADD CONSTRAINT uc_789fd29243f46d62b1c3aa8fe UNIQUE (student_id, exam_id);

ALTER TABLE lab_works
    ADD CONSTRAINT uc_878334a0fab26efbf85356d91 UNIQUE (course_id, lab_number);

ALTER TABLE students
    ADD CONSTRAINT uc_b12c52bbad81d5316a29ac337 UNIQUE (email);

ALTER TABLE tasks
    ADD CONSTRAINT uc_b498a5cce17a4e9eaa4518b85 UNIQUE (exam_id, variant_number);

ALTER TABLE exams
    ADD CONSTRAINT FK_EXAMS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE exam_submissions
    ADD CONSTRAINT FK_EXAM_SUBMISSIONS_ON_EXAM FOREIGN KEY (exam_id) REFERENCES exams (id);

ALTER TABLE exam_submissions
    ADD CONSTRAINT FK_EXAM_SUBMISSIONS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE exam_submissions
    ADD CONSTRAINT FK_EXAM_SUBMISSIONS_ON_TASK FOREIGN KEY (task_id) REFERENCES tasks (id);

ALTER TABLE lab_submissions
    ADD CONSTRAINT FK_LAB_SUBMISSIONS_ON_LAB_WORK FOREIGN KEY (lab_work_id) REFERENCES lab_works (id);

ALTER TABLE lab_submissions
    ADD CONSTRAINT FK_LAB_SUBMISSIONS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE lab_works
    ADD CONSTRAINT FK_LAB_WORKS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_EXAM FOREIGN KEY (exam_id) REFERENCES exams (id);

ALTER TABLE course_students
    ADD CONSTRAINT fk_coustu_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE course_students
    ADD CONSTRAINT fk_coustu_on_student FOREIGN KEY (student_id) REFERENCES students (id);
